sqlite_dir: ${SQLITE_DIR}
attachments_dir: ${ATTACHMENTS_DIR}
token: ${BOT_TOKEN}
zany_channel: ${ZANY_CHANNEL}
debug: 1
blacklist_user: true   # blacklists user from seeing it
command_prefix: ${COMMAND_PREFIX}


# economy items
economy_enable: true

economy:
    # currency and gain option
    currency_name: ${CURRENCY_NAME}
    max_bank: 1000000
    earn_interval: 360      # time in minutes
    per_interval_gain: 100  # how many unlocks gained per interval
    starting_amount: 500    # how much do you start with

    # rob settings
    rob_enabled: true       # can players rob
    rob_interval: 60        # rob interval in minutes
    rob_max: 100000         # max rob amount
    robs_per_interval: 5   # how many robs per interval

    # Authodelete cost
    delete_cost: 10         # cost of delete
    delete_timer: 0.3       # how many seconds to wait before deleting
