# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    environment: prod-env
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: stop old zany bot service
        run: sudo systemctl stop zany-bot.service

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Set runner-specific environment variables
        shell: bash
        run: |
          rm -rf .env
          echo "BOT_TOKEN=${{secrets.BOT_TOKEN}}\n" > .env 
          echo "ZANY_CHANNEL=${{secrets.ZANY_CHANNEL}}\n" >> .env 
          echo "COMMAND_PREFIX=${{secrets.COMMAND_PREFIX}}\n" >> .env 
          echo "CURRENCY_NAME=${{secrets.CURRENCY_NAME}}" >> .env 

      - name: make attachments folder
        run: mkdir attachments/

      - name: start new zany bot service
        run: sudo systemctl start zany-bot.service

      
