# This is a basic workflow to help you get started with Actions

name: Main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    environment: prod-env
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: stop old zany bot service
        run: sudo systemctl stop zany-bot.service

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          ref: main
          path: zany-bot


      - name: Set runner-specific environment variables
        shell: bash
        run: |
          printf '%s\n' 'BOT_TOKEN=${{secrets.BOT_TOKEN}}' 'ZANY_CHANNEL=${{secrets.ZANY_CHANNEL}}' 'COMMAND_PREFIX=${{secrets.COMMAND_PREFIX}}' 'ATTACHMENTS_DIR=${{secrets.ATTACHMENTS_DIR}}' 'CURRENCY_NAME=${{secrets.CURRENCY_NAME}}' 'SQLITE_DIR=${{secrets.SQLITE_DIR}}' > zany-bot/bot.env

      - name: start new zany bot service
        run: sudo systemctl start zany-bot.service

      
